name: "Build"

on:
  pull_request:
    branches:
      - develop
      - main
    paths-ignore:
      - "LICENSE"
      - "README.md"

  push:
    branches:
      - develop
      - main
    paths-ignore:
      - "LICENSE"
      - "README.md"

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
